[workspace]
git_only = true
git_release_enable = false
git_tag_enable = false
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
publish = false
release_always = false
semver_check = false

[[package]]
name = "nghe_api"

[[package]]
name = "nghe_proc_macro"

[[package]]
name = "nghe_frontend"

[[package]]
name = "nghe_backend"
git_tag_name = "v{{ version }}"
git_tag_enable = true
git_release_enable = true
