name: Create release PR

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: Version type to bump
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: cargo-edit
      - name: Bump version ${{ inputs.version-type }}
        run: cargo set-version --bump ${{ inputs.version-type }}
      - name: Regenerate Cargo.lock
        run: cargo update --workspace
      - name: Get new version
        id: cargo-version
        uses: mikefarah/yq@master
        with:
          cmd: yq '.workspace.package.version' Cargo.toml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: &title |
            chore: bump version to ${{ steps.cargo-version.outputs.result }}
          commit-message: *title
